// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: usercompany/usercompany.proto
//
// Copied from fio-auth-service/internal/grpc/pb/usercompany and vendored here
// so the client library has no runtime dependency on the server module.

package usercompany

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserCompanyService_CheckUser_FullMethodName                 = "/usercompany.UserCompanyService/CheckUser"
	UserCompanyService_CheckUserCompanyRelations_FullMethodName = "/usercompany.UserCompanyService/CheckUserCompanyRelations"
	UserCompanyService_CheckUserCompanyRole_FullMethodName      = "/usercompany.UserCompanyService/CheckUserCompanyRole"
	UserCompanyService_GetUserAllRelations_FullMethodName       = "/usercompany.UserCompanyService/GetUserAllRelations"
)

// UserCompanyServiceClient is the client API for UserCompanyService service.
type UserCompanyServiceClient interface {
	CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error)
	CheckUserCompanyRelations(ctx context.Context, in *CheckUserCompanyRelationsRequest, opts ...grpc.CallOption) (*CheckUserCompanyRelationsResponse, error)
	CheckUserCompanyRole(ctx context.Context, in *CheckUserCompanyRoleRequest, opts ...grpc.CallOption) (*CheckUserCompanyRoleResponse, error)
	GetUserAllRelations(ctx context.Context, in *GetUserAllRelationsRequest, opts ...grpc.CallOption) (*GetUserAllRelationsResponse, error)
}

type userCompanyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCompanyServiceClient(cc grpc.ClientConnInterface) UserCompanyServiceClient {
	return &userCompanyServiceClient{cc}
}

func (c *userCompanyServiceClient) CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserResponse)
	err := c.cc.Invoke(ctx, UserCompanyService_CheckUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCompanyServiceClient) CheckUserCompanyRelations(ctx context.Context, in *CheckUserCompanyRelationsRequest, opts ...grpc.CallOption) (*CheckUserCompanyRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserCompanyRelationsResponse)
	err := c.cc.Invoke(ctx, UserCompanyService_CheckUserCompanyRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCompanyServiceClient) CheckUserCompanyRole(ctx context.Context, in *CheckUserCompanyRoleRequest, opts ...grpc.CallOption) (*CheckUserCompanyRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserCompanyRoleResponse)
	err := c.cc.Invoke(ctx, UserCompanyService_CheckUserCompanyRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userCompanyServiceClient) GetUserAllRelations(ctx context.Context, in *GetUserAllRelationsRequest, opts ...grpc.CallOption) (*GetUserAllRelationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAllRelationsResponse)
	err := c.cc.Invoke(ctx, UserCompanyService_GetUserAllRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server-side stubs are included for completeness but are not used by the client.

type UserCompanyServiceServer interface {
	CheckUser(context.Context, *CheckUserRequest) (*CheckUserResponse, error)
	CheckUserCompanyRelations(context.Context, *CheckUserCompanyRelationsRequest) (*CheckUserCompanyRelationsResponse, error)
	CheckUserCompanyRole(context.Context, *CheckUserCompanyRoleRequest) (*CheckUserCompanyRoleResponse, error)
	GetUserAllRelations(context.Context, *GetUserAllRelationsRequest) (*GetUserAllRelationsResponse, error)
	mustEmbedUnimplementedUserCompanyServiceServer()
}

type UnimplementedUserCompanyServiceServer struct{}

func (UnimplementedUserCompanyServiceServer) CheckUser(context.Context, *CheckUserRequest) (*CheckUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUser not implemented")
}
func (UnimplementedUserCompanyServiceServer) CheckUserCompanyRelations(context.Context, *CheckUserCompanyRelationsRequest) (*CheckUserCompanyRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserCompanyRelations not implemented")
}
func (UnimplementedUserCompanyServiceServer) CheckUserCompanyRole(context.Context, *CheckUserCompanyRoleRequest) (*CheckUserCompanyRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserCompanyRole not implemented")
}
func (UnimplementedUserCompanyServiceServer) GetUserAllRelations(context.Context, *GetUserAllRelationsRequest) (*GetUserAllRelationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAllRelations not implemented")
}
func (UnimplementedUserCompanyServiceServer) mustEmbedUnimplementedUserCompanyServiceServer() {}
