// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercompany/usercompany.proto
//
// Copied from fio-auth-service/internal/grpc/pb/usercompany and vendored here
// so the client library has no runtime dependency on the server module.
// To regenerate: protoc --go_out=. --go_opt=paths=source_relative usercompany/usercompany.proto

package usercompany

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneCode     string                 `protobuf:"bytes,4,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBasic) Reset() {
	*x = UserBasic{}
	mi := &file_usercompany_usercompany_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasic) ProtoMessage() {}

func (x *UserBasic) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*UserBasic) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{0}
}

func (x *UserBasic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserBasic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBasic) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserBasic) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *UserBasic) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserBasic) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserCompanyRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCompanyRelation) Reset() {
	*x = UserCompanyRelation{}
	mi := &file_usercompany_usercompany_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCompanyRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCompanyRelation) ProtoMessage() {}

func (x *UserCompanyRelation) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*UserCompanyRelation) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{1}
}

func (x *UserCompanyRelation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCompanyRelation) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UserCompanyRelation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserCompanyRelation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CheckUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRequest) Reset() {
	*x = CheckUserRequest{}
	mi := &file_usercompany_usercompany_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRequest) ProtoMessage() {}

func (x *CheckUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	User          *UserBasic             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserResponse) Reset() {
	*x = CheckUserResponse{}
	mi := &file_usercompany_usercompany_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserResponse) ProtoMessage() {}

func (x *CheckUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CheckUserResponse) GetUser() *UserBasic {
	if x != nil {
		return x.User
	}
	return nil
}

type CheckUserCompanyRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserCompanyRelationsRequest) Reset() {
	*x = CheckUserCompanyRelationsRequest{}
	mi := &file_usercompany_usercompany_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserCompanyRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserCompanyRelationsRequest) ProtoMessage() {}

func (x *CheckUserCompanyRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserCompanyRelationsRequest) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUserCompanyRelationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserCompanyRelationsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type CheckUserCompanyRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Relations     []*UserCompanyRelation `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserCompanyRelationsResponse) Reset() {
	*x = CheckUserCompanyRelationsResponse{}
	mi := &file_usercompany_usercompany_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserCompanyRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserCompanyRelationsResponse) ProtoMessage() {}

func (x *CheckUserCompanyRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserCompanyRelationsResponse) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUserCompanyRelationsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CheckUserCompanyRelationsResponse) GetRelations() []*UserCompanyRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type CheckUserCompanyRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserCompanyRoleRequest) Reset() {
	*x = CheckUserCompanyRoleRequest{}
	mi := &file_usercompany_usercompany_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserCompanyRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserCompanyRoleRequest) ProtoMessage() {}

func (x *CheckUserCompanyRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserCompanyRoleRequest) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{6}
}

func (x *CheckUserCompanyRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserCompanyRoleRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CheckUserCompanyRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CheckUserCompanyRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Relation      *UserCompanyRelation   `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserCompanyRoleResponse) Reset() {
	*x = CheckUserCompanyRoleResponse{}
	mi := &file_usercompany_usercompany_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserCompanyRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserCompanyRoleResponse) ProtoMessage() {}

func (x *CheckUserCompanyRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckUserCompanyRoleResponse) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{7}
}

func (x *CheckUserCompanyRoleResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CheckUserCompanyRoleResponse) GetRelation() *UserCompanyRelation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type GetUserAllRelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAllRelationsRequest) Reset() {
	*x = GetUserAllRelationsRequest{}
	mi := &file_usercompany_usercompany_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAllRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllRelationsRequest) ProtoMessage() {}

func (x *GetUserAllRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetUserAllRelationsRequest) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserAllRelationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAllRelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Relations     []*UserCompanyRelation `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAllRelationsResponse) Reset() {
	*x = GetUserAllRelationsResponse{}
	mi := &file_usercompany_usercompany_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAllRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAllRelationsResponse) ProtoMessage() {}

func (x *GetUserAllRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usercompany_usercompany_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetUserAllRelationsResponse) Descriptor() ([]byte, []int) {
	return file_usercompany_usercompany_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserAllRelationsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUserAllRelationsResponse) GetRelations() []*UserCompanyRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

var File_usercompany_usercompany_proto protoreflect.FileDescriptor

const file_usercompany_usercompany_proto_rawDesc = "" +
	"\n" +
	"\x1dusercompany/usercompany.proto\x12\vusercompany\"\x92\x01\n" +
	"\tUserBasic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"phone_code\x18\x04 \x01(\tR\tphoneCode\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x80\x01\n" +
	"\x13UserCompanyRelation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"+\n" +
	"\x10CheckUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x11CheckUserResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.usercompany.UserBasicR\x04user\"Z\n" +
	" CheckUserCompanyRelationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"y\n" +
	"!CheckUserCompanyRelationsResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12>\n" +
	"\trelations\x18\x02 \x03(\v2 .usercompany.UserCompanyRelationR\trelations\"i\n" +
	"\x1bCheckUserCompanyRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"r\n" +
	"\x1cCheckUserCompanyRoleResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12<\n" +
	"\brelation\x18\x02 \x01(\v2 .usercompany.UserCompanyRelationR\brelation\"5\n" +
	"\x1aGetUserAllRelationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"s\n" +
	"\x1bGetUserAllRelationsResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12>\n" +
	"\trelations\x18\x02 \x03(\v2 .usercompany.UserCompanyRelationR\trelations2\xb3\x03\n" +
	"\x12UserCompanyService\x12J\n" +
	"\tCheckUser\x12\x1d.usercompany.CheckUserRequest\x1a\x1e.usercompany.CheckUserResponse\x12z\n" +
	"\x19CheckUserCompanyRelations\x12-.usercompany.CheckUserCompanyRelationsRequest\x1a..usercompany.CheckUserCompanyRelationsResponse\x12k\n" +
	"\x14CheckUserCompanyRole\x12(.usercompany.CheckUserCompanyRoleRequest\x1a).usercompany.CheckUserCompanyRoleResponse\x12h\n" +
	"\x13GetUserAllRelations\x12'.usercompany.GetUserAllRelationsRequest\x1a(.usercompany.GetUserAllRelationsResponseB/Z-fio-auth-service/internal/grpc/pb/usercompanyb\x06proto3"

var (
	file_usercompany_usercompany_proto_rawDescOnce sync.Once
	file_usercompany_usercompany_proto_rawDescData []byte
)

func file_usercompany_usercompany_proto_rawDescGZIP() []byte {
	file_usercompany_usercompany_proto_rawDescOnce.Do(func() {
		file_usercompany_usercompany_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usercompany_usercompany_proto_rawDesc), len(file_usercompany_usercompany_proto_rawDesc)))
	})
	return file_usercompany_usercompany_proto_rawDescData
}

var file_usercompany_usercompany_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_usercompany_usercompany_proto_goTypes = []any{
	(*UserBasic)(nil),                         // 0: usercompany.UserBasic
	(*UserCompanyRelation)(nil),               // 1: usercompany.UserCompanyRelation
	(*CheckUserRequest)(nil),                  // 2: usercompany.CheckUserRequest
	(*CheckUserResponse)(nil),                 // 3: usercompany.CheckUserResponse
	(*CheckUserCompanyRelationsRequest)(nil),  // 4: usercompany.CheckUserCompanyRelationsRequest
	(*CheckUserCompanyRelationsResponse)(nil), // 5: usercompany.CheckUserCompanyRelationsResponse
	(*CheckUserCompanyRoleRequest)(nil),       // 6: usercompany.CheckUserCompanyRoleRequest
	(*CheckUserCompanyRoleResponse)(nil),      // 7: usercompany.CheckUserCompanyRoleResponse
	(*GetUserAllRelationsRequest)(nil),        // 8: usercompany.GetUserAllRelationsRequest
	(*GetUserAllRelationsResponse)(nil),       // 9: usercompany.GetUserAllRelationsResponse
}
var file_usercompany_usercompany_proto_depIdxs = []int32{
	0, // 0: usercompany.CheckUserResponse.user:type_name -> usercompany.UserBasic
	1, // 1: usercompany.CheckUserCompanyRelationsResponse.relations:type_name -> usercompany.UserCompanyRelation
	1, // 2: usercompany.CheckUserCompanyRoleResponse.relation:type_name -> usercompany.UserCompanyRelation
	1, // 3: usercompany.GetUserAllRelationsResponse.relations:type_name -> usercompany.UserCompanyRelation
	2, // 4: usercompany.UserCompanyService.CheckUser:input_type -> usercompany.CheckUserRequest
	4, // 5: usercompany.UserCompanyService.CheckUserCompanyRelations:input_type -> usercompany.CheckUserCompanyRelationsRequest
	6, // 6: usercompany.UserCompanyService.CheckUserCompanyRole:input_type -> usercompany.CheckUserCompanyRoleRequest
	8, // 7: usercompany.UserCompanyService.GetUserAllRelations:input_type -> usercompany.GetUserAllRelationsRequest
	3, // 8: usercompany.UserCompanyService.CheckUser:output_type -> usercompany.CheckUserResponse
	5, // 9: usercompany.UserCompanyService.CheckUserCompanyRelations:output_type -> usercompany.CheckUserCompanyRelationsResponse
	7, // 10: usercompany.UserCompanyService.CheckUserCompanyRole:output_type -> usercompany.CheckUserCompanyRoleResponse
	9, // 11: usercompany.UserCompanyService.GetUserAllRelations:output_type -> usercompany.GetUserAllRelationsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_usercompany_usercompany_proto_init() }
func file_usercompany_usercompany_proto_init() {
	if File_usercompany_usercompany_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usercompany_usercompany_proto_rawDesc), len(file_usercompany_usercompany_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usercompany_usercompany_proto_goTypes,
		DependencyIndexes: file_usercompany_usercompany_proto_depIdxs,
		MessageInfos:      file_usercompany_usercompany_proto_msgTypes,
	}.Build()
	File_usercompany_usercompany_proto = out.File
	file_usercompany_usercompany_proto_goTypes = nil
	file_usercompany_usercompany_proto_depIdxs = nil
}
